### ISSUE TITLE
Possible security issue: any IP can be blocked

### ISSUE THREAD

**Issue by Lekensteyn** [sofar/tallow#1]
Usernames in SSH log entries can actually contain spaces. If someone tries to login as `x x x 1.2.3.4`, the log will contain:

```
Invalid user x x x 1.2.3.4 from <attacker ip>
```

This will cause "1.2.3.4" to be blocked instead of <attacker ip>.

Today I finished systemd support on https://github.com/Lekensteyn/ssh-blocker. Note that it does not have regexes for the "Failed password for invalid user" since I use keys only and use messages from sshd, not PAM. It is trivial to add more matches though (regex.c)

**Comment by robert-scheck** [comment]
@sofar, do you have any intentions to catch such a case with tallow?

**Comment by sofar** [comment]
Right, I certainly see that fixed... Hadn't had the time to update this, so it slipped off my radar.

**Comment by sofar** [comment]
e296f501c700bbe84a2024134f07d81096018621
